# Generated by Django 3.2.9 on 2022-09-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_todo_app_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_app',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
